### ISSUE TITLE
Several errors thrown when trying to connect

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#562] opened 2022-01-24 15:34 UTC
I suspect this is an issue with the Oauth2 authentication. I'm using the same configurations that worked last time. When hitting Test connection or making a search I'm redirected throw the Oatuh2 flow and I end up onto the usual confirm page:

![image](https://user-images.githubusercontent.com/571129/150813005-b3ecde8c-6b88-49c5-8f47-87db29cf1096.png)

However the plugin throws the following exceptions. I've looked into the network debugger and all the responses are 200, so everything looks ok, unless the real response is the login page. But I can't spot it from the network panel.

![image](https://user-images.githubusercontent.com/571129/150813294-78d6eeca-745b-4dba-967c-c33d3606a7b4.png)

![image](https://user-images.githubusercontent.com/571129/150813327-61f1f978-ca4d-4830-86fb-786fada84231.png)

**Comment by ricardogsilva** [comment] 2022-02-04 22:16
@giohappy I was not able to replicate this while connecting to both 

- https://master.demo.geonode.org
- https://dev.nexus.geosolutionsgroup.com

I tried with and without authentication (OAuth2)

Maybe you were using a different GeoNode deployment when you got this error? Please provide a bit more detail so that I may be able to replicate the issue

**Comment by ricardogsilva** [comment] 2022-02-09 18:16
I guess we can close this issue, since it seems to not be reproducible. Additionally, we now have Basic Auth as the preferred connection method

**Closed** 2022-02-09 20:15 UTC
Labels: bug, QGIS Client
