### ISSUE TITLE
[Harvesters] "Perform harvesting" action keeps re-harvesting all the resources marked "should_be_harvested = True" again

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#448] opened 2021-09-21 15:16 UTC
What's the difference between the actions "Update harvestable resources" and "Perform harvesting"?

I noticed that there's not way to add just one more resource to the list and harvest just this one. The "Perform harvesting" operation keeps harvesting again all the resources from scratch.

This approach is not scalable.

**Comment by giohappy** [comment] 2021-09-21 15:32
@afabiani "Update harvestable resources" updates the list of available remote resources (harvestable resources).
"Perform harvesting" executes the harvesting of the harvestable resources marked to be harvested ("Should be harvested").

Notice that each harvester client supports a set of filters that can be put inside the harvester configuration.
For example, the GeoNode legacy harvester implements [this filters](https://github.com/GeoNode/geonode/blob/master/geonode/harvesting/harvesters/geonode.py#L147-L187). I'm using them, for example, to differentiate the harvesting of documents from datasets (layers in legacy terms).

### Open questions
**Update the list of harvestable resources**. How can we ask the remote server to only return new resources? For GeoNode we might add a flag and automatically set a date filter from the last retrieval of the list harvestable resources. However you would miss any remote update (deleted and updated resources on the remote servier).

"Harvesting of the resources". For the moment we have the flag "Should be harvested" to avoid repeating the harvesting of the remote resource (which would be required in case of updates).

*WMS server* in this case date based filtering is not available of course, so updating the list of resources and the resource itself requires a full retrieval + harvesting.

How would you improve the current logic @afabiani?

**Comment by ricardogsilva** [comment] 2021-09-21 15:38
This is intended behavior.

I am at fault here, for not having provided some good docs on the harvesting yet.

The workflow that I have implemented is similar to the way the GeoNode remote services works - it is something we discussed initially, together with @giohappy 

It goes like this:

1. User adds a new harvester, along with its configuration;
2. Upon saving the harvester, GeoNode proceeds to check the remote service and retrieve a list of existing resources on the remote that can be harvested by GeoNode. These are stored locally as instances of `harvesting.models.HarvestableResource`. This is simply a list of what is there on the remote and does not imply that those resources will be harvested by GeoNode;
3. User visits the harvestable resources page on the admin section (or via the API) and selects those resources that are interesting by setting their `should_be_harvested` property to `True`. This signals to GeoNode that the next time a new harvesting operation occurs those remote resources must be harvested;
4. When the time comes (either via automated scheduling or manually by some user action) a new harvesting session starts. For each `HarvestableResource` that has `should_be_harvested=True`, GeoNode proceeds to harvest the corresponding data from the remote service. This results in the creation (or update) of a new GeoNode resource (_i.e._ `Dataset`, `Document` etc) for each relevant `HarvestableResource`.
5. There is a relationship between `HarvestableResource` and GeoNode `base.ResourceBase` objects. This is useful for relating the two concepts;
6. Each time there is a new harvesting session, GeoNode check all relevant `HarvestableResource`s again - the reason for this is that the remote resources may have changed and we want to synchronize the changes with the local resources.

**Comment by afabiani** [comment] 2021-09-22 08:18
@ricardogsilva ok with the flow, but in this case I need the `should_be_harvested` property set back to `False` once the session has finished.

**Comment by giohappy** [comment] 2021-09-22 09:11
@afabiani if you set it to `False` automatically you loose the ability to update the resource if a scheduled harvesting is configured.

**Comment by afabiani** [comment] 2021-09-22 09:20
@giohappy @ricardogsilva in that case we need a way to add a single resource to the active harvester. The easier way, without changing the current paradigm, would be to allow the worker to be able to harvest a single `resource_id`, otherwise we might need another `flag` in order to instruct the `harvester` to **not update** some resources.

What do you think about that?

_further options_: Update the `filters` every time with `start-date` and `end-date`, could this be a possible solution? Nevertheless I'm not really comfortable with this one.

**Comment by ricardogsilva** [comment] 2021-09-22 09:27
@afabiani what you request is made possible by geonode/geonode#7947 (soon to be merged)

It is now possible to visit the django admin section of the harvestable resources, select some of them, and then use the `harvest_selected_resources` action directly.

This means you can harvest a resource individually outside of the usual concept of the harvesting session where everything that has `should_be_harvested=True` is harvested everytime. This can even be done for those resources that have `should_be_harvested=False`.

Does this implementation sound good to you?

**Comment by afabiani** [comment] 2021-09-22 09:30
@ricardogsilva that seems good, I will test this feature once 7947 will be merged

**Comment by giohappy** [comment] 2021-09-22 09:30
@afabiani is it something available for any harvester or just for GeoNode?

**Comment by ricardogsilva** [comment] 2021-09-22 16:19
@giohappy I confirm this is available for any harvester

**Closed** 2021-09-27 13:35 UTC
Labels: bug, Harvester
